### ISSUE TITLE
mage deploy fails with "execute-change-set failed: ROLLBACK_COMPLETE" creating changeset for ACM

### ISSUE THREAD

**Issue by kbroughton** [panther-labs/panther#118]
**Describe the bug**

**To Reproduce**

0. git clone https://github.com/panther-labs/panther --depth 1 --branch v0.1.1
1. run ./dev.sh which ends by exec'ing into the container
2. set the AWS_ variables
2. mage deploy
3. See error

**Expected behavior**
mage deploy completes without error

**Screenshots**
deploy: cloudformation package deployments/backend.yml => out/deployments/package.backend.yml
deploy: downloading boto3==1.10.46,policyuniverse==1.3.2.1,requests==2.22.0
ERROR: awscli 1.17.7 has requirement botocore==1.14.7, but you'll have botocore 1.13.50 which is incompatible.
ERROR: awscli 1.17.7 has requirement s3transfer<0.4.0,>=0.3.0, but you'll have s3transfer 0.2.1 which is incompatible.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
deploy: uploading out/layer.zip to s3://panther-source-111111111111-us-east-1/layers/python-analysis.zip
deploy: uploading ACM certificate
deploy: WARNING no ACM certificate ARN provided and no certificate file provided, generating a self-signed certificate
deploy: panther-app: CreateChangeSet: CREATE_PENDING
deploy: panther-app: CreateChangeSet: CREATE_COMPLETE
deploy: panther-app: ExecuteChangeSet: CREATE_IN_PROGRESS
deploy: panther-app: ExecuteChangeSet: ROLLBACK_IN_PROGRESS
deploy: panther-app: ExecuteChangeSet: ROLLBACK_COMPLETE
Error: execute-change-set failed: ROLLBACK_COMPLETE:

Then mage deploy halts.

**Environment**
./dev.sh

- Panther version or commit: v0.1.1
- OS: 10.14.6
- Browser: chrome

**Additional context**
fresh pull
AWS user has admin privs

**Comment by nhakmiller** [comment]
Thanks for the detailed bug report.

Based on the output provided, the ACM certificate appears to have uploaded correctly at least. We recently fixed some bugs related to deploying in `us-east-1`, so I will test a deployment of v0.1.1 in `us-east-1` and see if that's possibly related.

Would you be able to provide any output from the AWS CloudFormation console? From both `panther-app` and any nested stacks that experienced an error.

**Comment by nhakmiller** [comment]
I deployed a few times to try to replicate this issue, including cloning the repository fresh and deploying it into an empty `us-east-1` region (no `panther-buckets`, `panther-app`, or any other panther related stacks or resources), but I was unable to do so.

Did the deployment fail immediately after it began, or did it run for a while? I think I'll need to see the CloudFormation console messages to help troubleshoot the issue further.

**Comment by kbroughton** [comment]
I tried the following:
- Deleted the stack. 
- Created a public ACM manually
- Added it's arn to deployments/panther_config.yml
- mage clean
- mage deploy
```
deploy: panther-buckets: no changes needed
build:lambda: go build internal/*/main (21 binaries)
deploy: cloudformation package deployments/backend.yml => out/deployments/package.backend.yml
deploy: s3://panther-source-111111111111-us-east-1/layers/python-analysis.zip exists and is up to date
deploy: panther-app: CreateChangeSet: CREATE_PENDING
deploy: panther-app: CreateChangeSet: CREATE_COMPLETE
deploy: panther-app: ExecuteChangeSet: CREATE_IN_PROGRESS
deploy: panther-app: ExecuteChangeSet: ROLLBACK_IN_PROGRESS
deploy: panther-app: ExecuteChangeSet: ROLLBACK_COMPLETE
Error: execute-change-set failed: ROLLBACK_COMPLETE:
```

This time the cloudformation errors start with:
```
Embedded stack arn:aws:cloudformation:us-east-1:111111111111:stack/panther-app-WebApplicationNetworking-AOJ72QPXXXXXX/407aeb80-4881-11ea-afe7-00000000000 was not successfully created: The following resource(s) failed to create: [InternetGateway, VPC].
```
It failed much faster this time.
Are the python errors a problem, or erroneous? I will try deploying into a clean AWS account later.

**Comment by nhakmiller** [comment]
That's interesting, I have never seen that error before. Can you go into the resources tab of the `panther-app` stack, then find the `panther-app-WebApplicationNetworking-ZZZ` stack and click through to see the events there? Annoyingly CloudFormation automatically removes failed nested stacks from the console during the initial deployment, but you can still click through to them from the root stack.

The python errors are not an issue.

**Comment by austinbyers** [comment]
> Annoyingly CloudFormation automatically removes failed nested stacks from the console during the initial deployment

Right, CloudFormation errors are somewhat annoying to track down. You can still see deleted stacks, you just have to change the filter in the CloudFormation console to show them. So like @nhakmiller suggested, if you go to the `panther-app-WebApplicationNetworking-ZZZ` stack and view the stack events or resources, you should see some error messages. Only one of the error messages will be relevant - the others will just say "resource failed to create" because the stack was cancelled.

I'll make a related issue about better error handling for failed deployments

**Comment by nhakmiller** [comment]
I'm going to go ahead and close this for two reasons:

1. Inactivity
2. The deployment process has dramatically changed since this issue was created, and whatever the root cause was is probably no longer applicable.

If these issues persist on the latest tagged release, please open a new issue.

**Comment by kbroughton** [comment]
Thanks and sorry I dropped.  I do not have this issue any longer with more recent releases.
